### ISSUE TITLE
error building fanx from source

### ISSUE THREAD

**Issue by fraya** [fanx-dev/fanx#1]
I can't build fanx from sources:
 
    $ cd Workspace
    $ git clone ...
    $ cd fanx
    $ export PATH=$PATH:/home/fraya/Workspace/fanx/env/bin/
    $ fan -version
    $ Fanx Launcher 
       ...
          java.version:   11.0.5
          fanx.version:   2.1
          fan.home:       /home/fraya/Workspace/fanx/env/
          Env Path:
              ~/Workspace/fanx/
              ~/Workspace/fanx/env/
    $ cd src
    $ sh build_all.sh
    bootstrap build from ../release/fanx-2.2/bin/fanb to /home/fraya/Workspace/fanx/src/../env/
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    ...
    build sys and std
    bootstrap.sh: line 18: ../release/fanx-2.2/bin/fanb: No such file or directory

**Comment by chunquedong** [comment]
It require an old releases to bootstrap build.  download the latest release (fanx-2.2.zip) and unzip to release dir.

**Comment by fraya** [comment]
I am sorry for the inconvenience!

**Comment by chunquedong** [comment]
Not at all. Did it work?

**Comment by fraya** [comment]
Thank you for your interest. Not yet.

        ERR: Invalid configDir URI for 'jdkHome': /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/
        sys::Err ERR: Must config build prop 'jdkHome'

**Comment by chunquedong** [comment]
The jdkHome setting in ./env/etc/build/config.props and ./release/fanx-2.2/etc/build/config.props

**Comment by fraya** [comment]
Ok. Some advance, but an error in testing:

    testCompiler/pod.props: Cannot resolve depend: pod 'concurrent' not found
    BUILD FAILED [817ms]!

**Comment by chunquedong** [comment]
The core code is already build success. and you can run it by 'fanb concurrent/pod.props'.
I will fix the build order later.

**Comment by chunquedong** [comment]
Fixed in v3.0

**Comment by chunquedong** [comment]
Fixed in v3.0
