### ISSUE TITLE
Add support for the existing F4 IDE?

### ISSUE THREAD

**Issue by ghost** [fanx-dev/fanx#10]
Could you add Fanx support to the existing F4 IDE? This is the most complete and production ready IDE for Fantom in the market now.

**Comment by chunquedong** [comment]
Sorry, It's not in the plan. The FantomIDE(netbeans plugin) code is more easy for me.

**Comment by ghost** [comment]
> Sorry, It's not in the plan. The FantomIDE(netbeans plugin) code is more easy for me.

You should update FanIDE. F4 seems to be more active developed.
