### ISSUE TITLE
请问打算将报错等等反馈信息中文化吗？

### ISSUE THREAD

**Issue by nobodxbodon** [fanx-dev/fanx#2]
很高兴看到中文语法和 API。
另外，个人认为反馈信息也是开发中的一个痛点，之前借助木兰作了个[演示](https://zhuanlan.zhihu.com/p/144809020)，请见“运行源码文件有错时反馈中文信息”一图。

BTW 是在 [oschina](https://www.oschina.net/news/116270/fanx-3-2-released) 上看到的。

**Comment by chunquedong** [comment]
将来会支持，但不是高优先级工作。目前的工作重点是优化Android APP开发体验。

**Comment by nobodxbodon** [comment]
Android API 中文化的量不小吧？打算参考火山等等的接口设计吗？

**Comment by chunquedong** [comment]
可能让你失望了，API并不是中文的。

**Comment by nobodxbodon** [comment]
没事，要是已经有的话倒有点意外，因为 API 中文化很难一蹴而就，早先[讨论过](https://github.com/program-in-chinese/overview/issues/54)对现有标准库的中文化，后来发现中文术语有待成系统。个人知道的在逐步进行 API 中文化的开源项目有[草蟒](https://zhuanlan.zhihu.com/p/102811665)。
