### ISSUE TITLE
语法建议

### ISSUE THREAD

**Issue by toop** [fanx-dev/fanx#6]
text :=  “test”
echo("${text}")
// "test"
//or
echo("{text}")
// "test

同时建议增加when语法，谢谢！

**Comment by chunquedong** [comment]
字符串插入语法是支持的，有什么问题吗？
when是怎样的？

**Comment by toop** [comment]
给个伪代码:
guest :=input(int num)
when(num){
  100 -> echo("你输入了100")
  200 -> echo("你输入了200")
  else -> echo("你输入的{num}不符合要求")
}

**Comment by chunquedong** [comment]
这种switch语句已经实现了：
```
switch(num){
case 100: echo("你输入了100")
case 100: echo("你输入了200")
default: echo("你输入的${num}不符合要求")
}
```
