### ISSUE TITLE
关于类继承的建议

### ISSUE THREAD

**Issue by toop** [fanx-dev/fanx#7]
建议类和方法默认为final类型，不可继承；若要继承，建议用open，virtual感觉上怪怪的。另外interface应该有。

**Comment by chunquedong** [comment]
这些功能都有，可能是文档没写清楚。默认就是final，类型和方法都可以用virtual修饰。iterface这边叫mixin。

**Comment by toop** [comment]
我的意思是把virtual换成open，virtual让人产生歧义

**Comment by chunquedong** [comment]
C++、Java都用virtual，业界已经习惯了，如果换成其他的没有太多收益。

**Comment by toop** [comment]
kotlin用的是open
